[package]
name = "uom_ng"
version = "0.1.0"
edition = "2021"

[lib]
name = "uom_ng"

[dependencies]
derivative = "2.2.0"
paste = "1.0.6"
typenum = { version = "1.15.0", default-features = false }

[dev-dependencies]
similar-asserts = "1.2.0"
